# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number_of_openings', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
