# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='description',
            field=models.TextField(default='no description', max_length=300),
            preserve_default=False,
        ),
    ]
