# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
