# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_person_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isLeadership',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
