# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0009_person_isleadership'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scanner.Person')),
                ('periods', models.CharField(max_length=18)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scanner.person',),
        ),
        migrations.RemoveField(
            model_name='person',
            name='isLeadership',
        ),
    ]
