# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_auto_20170902_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipmember',
            name='can_add_leadership_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
