# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_leadershipmember_can_change_leadership_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cad_3d_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='electronics_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='printing_3d_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='sewing_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='video_editing_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='vinyl_cutting_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='hours',
            field=models.FloatField(default=0),
        ),
    ]
