# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_auto_20170910_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cad_2d_level',
            field=models.IntegerField(default=0),
        ),
    ]
