# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_person_cad_2d_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_letter', models.IntegerField()),
                ('period_number', models.IntegerField()),
                ('individual_spots', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Period')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Period')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_off', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.ScheduleDay'),
        ),
    ]
