# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_auto_20170920_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleday',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='schedule',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
