# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_auto_20170922_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_letter',
            field=models.CharField(max_length=5),
        ),
    ]
